/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

public class ViewFormMain extends javax.swing.JFrame {
 
  
    /**
     * Creates new form Iniciar
     */
    
    public ViewFormMain() {
        
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTextConvertFrom = new javax.swing.JLabel();
        jTextInsert = new javax.swing.JTextField();
        jLabelTextTo = new javax.swing.JLabel();
        jTextConverted = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextConvertFrom.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextConvertFrom.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelTextConvertFrom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextConvertFrom.setText("Convert from");
        getContentPane().add(jLabelTextConvertFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 100));

        jTextInsert.setDoubleBuffered(true);
        getContentPane().add(jTextInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, 70));

        jLabelTextTo.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelTextTo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextTo.setText("To");
        getContentPane().add(jLabelTextTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jTextConverted.setText(" ");
        getContentPane().add(jTextConverted, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 150, 70));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 300, 70));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 300, 70));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FundoView1.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 800, 340));

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(806, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelTextConvertFrom;
    private javax.swing.JLabel jLabelTextTo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JTextField jTextConverted;
    private javax.swing.JTextField jTextInsert;
    // End of variables declaration//GEN-END:variables
}



























