/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.view;

import java.util.List;
import program.VisualizeConvertersFiles;
import converters.ClassInterface.AbstractConverter;
import java.awt.event.ItemEvent;

public class ViewFormMain extends javax.swing.JFrame {
    
    private boolean changedOptionJComboBox01 = false;
    /**
     * Creates new form Iniciar
     */
    public ViewFormMain() {

        initComponents();

        try {

            VisualizeConvertersFiles visualizeArchivesConverters = new VisualizeConvertersFiles();
            List<String> listWithNamesArchivesInDirectoryConverters = visualizeArchivesConverters.VisualizeConvertersFiles();

            for (String listNameArchive : listWithNamesArchivesInDirectoryConverters) {

                AbstractConverter newInstance = (AbstractConverter) Class.forName(listNameArchive).getConstructor().newInstance();
                jComboBox01ConvertFrom.addItem(newInstance.getDescriptionClassConverter() + ": " + listNameArchive);
               
            }
            
            jComboBox01ConvertFrom.setSelectedIndex(-1);
            changedOptionJComboBox01= true;
            
        } catch (Exception e) {
            // TODO Auto-generated catch block
            System.out.println(e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTextConvertFrom = new javax.swing.JLabel();
        jTextInsert = new javax.swing.JTextField();
        jLabelTextTo = new javax.swing.JLabel();
        jTextConverted = new javax.swing.JTextField();
        jComboBox01ConvertFrom = new javax.swing.JComboBox<>();
        jComboBox2To = new javax.swing.JComboBox<>();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextConvertFrom.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextConvertFrom.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelTextConvertFrom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextConvertFrom.setText("Convert from");
        getContentPane().add(jLabelTextConvertFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 100));

        jTextInsert.setDoubleBuffered(true);
        getContentPane().add(jTextInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, 70));

        jLabelTextTo.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelTextTo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextTo.setText("To");
        getContentPane().add(jLabelTextTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jTextConverted.setText(" ");
        getContentPane().add(jTextConverted, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 150, 70));

        jComboBox01ConvertFrom.setMaximumRowCount(200);
        jComboBox01ConvertFrom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox01ConvertFrom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ConvertersIClasstemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox01ConvertFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 530, 70));

        jComboBox2To.setMaximumRowCount(200);
        jComboBox2To.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2To.setEnabled(false);
        getContentPane().add(jComboBox2To, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 530, 70));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FundoView1.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-16, 0, 1380, 390));

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(1061, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertersIClasstemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ConvertersIClasstemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED && changedOptionJComboBox01) {

            try {
                jComboBox2To.setEnabled(true);
                System.out.println("AAA");
                
            } catch (Exception e) {
                // TODO Auto-generated catch block
                System.out.println(e);

            }
        }
    }//GEN-LAST:event_ConvertersIClasstemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox01ConvertFrom;
    private javax.swing.JComboBox<String> jComboBox2To;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelTextConvertFrom;
    private javax.swing.JLabel jLabelTextTo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JTextField jTextConverted;
    private javax.swing.JTextField jTextInsert;
    // End of variables declaration//GEN-END:variables
}
